name: lipshift
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - asttokens
  - bzip2
  - ca-certificates
  - comm
  - decorator
  - exceptiongroup
  - executing
  - expat
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libsodium
  - libstdcxx-ng
  - libuuid
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - platformdirs
  - prompt-toolkit
  - ptyprocess
  - pure_eval
  - pygments
  - python
  - python-dateutil
  - readline
  - six
  - sqlite
  - stack_data
  - tk
  - traitlets
  - typing_extensions
  - wcwidth
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
    - absl-py
    - accelerate
    - aiohappyeyeballs
    - aiohttp
    - aiosignal
    - albumentations
    - alembic
    - annotated-types
    - appdirs
    - attrs
    - autoattack
    - beautifulsoup4
    - bleach
    - certifi
    - charset-normalizer
    - class-resolver
    - click
    - click-default-group
    - colorlog
    - contourpy
    - cycler
    - dataclasses-json
    - datasets
    - debugpy
    - dill
    - docdata
    - docker-pycreds
    - einops
    - entmax
    - evdev
    - filelock
    - fonttools
    - frozenlist
    - fsspec
    - gdown
    - geotorch
    - gitdb
    - gitpython
    - greenlet
    - grpcio
    - huggingface
    - huggingface-hub
    - idna
    - imageio
    - jinja2
    - joblib
    - jsonschema
    - jsonschema-specifications
    - jupyter-core
    - kaggle
    - kiwisolver
    - lazy-loader
    - mako
    - markdown
    - markupsafe
    - marshmallow
    - matplotlib
    - more-click
    - more-itertools
    - mpmath
    - msgpack
    - multidict
    - multiprocess
    - munch
    - mypy-extensions
    - networkx
    - numpy
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - opencv-python-headless
    - optuna
    - pandas
    - pillow
    - pip
    - pix2tex
    - protobuf
    - psutil
    - pyarrow
    - pyarrow-hotfix
    - pydantic
    - pydantic-core
    - pykeen
    - pynput
    - pyparsing
    - pyqt6
    - pyqt6-qt6
    - pyqt6-sip
    - pyqt6-webengine
    - pyqt6-webengine-qt6
    - pyside6
    - pyside6-addons
    - pyside6-essentials
    - pysocks
    - pystow
    - python-slugify
    - python-xlib
    - pytorch-ignite
    - pytz
    - pyyaml
    - pyzmq
    - ray
    - referencing
    - regex
    - requests
    - robustbench
    - rpds-py
    - safetensors
    - scikit-image
    - scikit-learn
    - scipy
    - screeninfo
    - seaborn
    - sentry-sdk
    - setproctitle
    - setuptools
    - shiboken6
    - smmap
    - soupsieve
    - sqlalchemy
    - sympy
    - tabulate
    - tensorboard
    - tensorboard-data-server
    - tensorboardx
    - text-unidecode
    - threadpoolctl
    - tifffile
    - timm
    - tokenizers
    - torch
    - torch-max-mem
    - torch-ppr
    - torchdiffeq
    - torchvision
    - tornado
    - tqdm
    - transformers
    - triton
    - typing-inspect
    - tzdata
    - urllib3
    - wandb
    - webencodings
    - werkzeug
    - wheel
    - x-transformers
    - xxhash
    - yacs
    - yarl
      